import { createClient } from '@supabase/supabase-js';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '../../config/constants';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('Supabase credentials are missing. Please configure environment variables.');
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

// Database types (will be generated by Supabase)
export type Database = {
  public: {
    Tables: {
      pacientes: {
        Row: {
          id: string;
          documento: string;
          nombre: string;
          fecha_nacimiento: string;
          edad: number | null;
          telefono: string | null;
          direccion: string | null;
          email: string | null;
          metrosalud_id: string | null;
          metrosalud_sync_at: string | null;
          estado: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['pacientes']['Row'], 'id' | 'created_at' | 'updated_at' | 'edad'>;
        Update: Partial<Database['public']['Tables']['pacientes']['Insert']>;
      };
      historias_clinicas: {
        Row: {
          id: string;
          paciente_id: string;
          fecha_apertura: string;
          motivo_consulta: string;
          enfermedad_actual: string;
          antecedentes: string | null;
          examen_fisico: string | null;
          diagnostico: string;
          plan_tratamiento: string;
          profesional_apertura: string;
          estado: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['historias_clinicas']['Row'], 'id' | 'created_at' | 'updated_at' | 'fecha_apertura'>;
        Update: Partial<Database['public']['Tables']['historias_clinicas']['Insert']>;
      };
      procedimientos: {
        Row: {
          id: string;
          historia_clinica_id: string;
          tipo: string;
          titulo: string;
          fecha: string;
          datos: Record<string, any>;
          profesional: string;
          observaciones: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['procedimientos']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['procedimientos']['Insert']>;
      };
      fotos_clinicas: {
        Row: {
          id: string;
          procedimiento_id: string;
          nombre: string;
          descripcion: string | null;
          url: string;
          thumbnail_url: string | null;
          mime_type: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          tipo: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['fotos_clinicas']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['fotos_clinicas']['Insert']>;
      };
    };
  };
};
